[project]
name = "day-03"
version = "2025.12"
description = "Advent of Code 2025 - Day 03"
authors = [
    { name = "Teja Vishwanadha", email = "496868+tvishwanadha@users.noreply.github.com" }
]
requires-python = ">=3.14.0"
dependencies = []

[project.scripts]
day_03 = "day_03.solution:main"

[build-system]
requires = ["uv_build>=0.9.11,<0.10.0"]
build-backend = "uv_build"
