[project]
name = "day-04"
version = "2025.12"
description = "Advent of Code 2025 - Day 04: Printing Department"
authors = [
    { name = "Teja Vishwanadha", email = "496868+tvishwanadha@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
day_04 = "day_04.solution:main"

[build-system]
requires = ["uv_build>=0.9.15,<0.10.0"]
build-backend = "uv_build"
