[project]
name = "day-01"
version = "2025.12"
description = "Advent of Code 2025 - Day 01: Safe Combination"
authors = [
    { name = "Teja Vishwanadha", email = "496868+tvishwanadha@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
day_01 = "day_01.solution:main"

[build-system]
requires = ["uv_build>=0.9.11,<0.10.0"]
build-backend = "uv_build"
